#!/bin/bash

# Default to ENU if nothing passed in as first arg
if [ ".$1" == "." ]; then WINLANG="ENU"; else WINLANG="$1"; fi

# Look for URL|LANG in scripts/ + second arg
for needed in `egrep -hri "URL\|($WINLANG|ALL)" scripts/$2 | tr ' ' '~'`; do
    url=`echo "$needed" | cut -d\| -f3 | tr '~' ' ' | perl -pe 's/\r//;s/^ *//;s/ *$//'`
    file=`echo "$needed" | cut -d\| -f4 | tr '~' ' '  | perl -pe 's/\r//;s/^ *//;s/ *$//'`
    path=`echo "$file" | perl -pe 's#(.*/).*#$1#'`

    # Make sure path is available
    mkdir -p "$path"
    # Download file if it doesn't exist
    if [ ! -f "$file" ] ; then
        if wget --passive-ftp -O "$file.$$.tmp" "$url" ; then
            mv "$file.$$.tmp" "$file"
        else
            rm -f "$file.$$.tmp"
        fi
    fi
done
