      <!-- ##### Right Sidebar ##### -->


  <div class="rightSideBar doNotPrint">

  <p class="sideBarTitle">News</p>

  <div class="sideBarText"><strong>Release Candidate</strong><br/>
     <a href="http://unattended.sourceforge.net/testing/48rc6/">4.8 RC6</a>
  </div>
  <div class="sideBarText"><strong>Changelog</strong><br />
    <a href="http://unattended.cvs.sourceforge.net/*checkout*/unattended/unattended/NEWS.txt?revision=HEAD">version 4.7</a>
  </div>
  <a href="http://sourceforge.net/news/?group_id=62053" class="more">more news &raquo;</a>

  <p class="sideBarTitle">Downloads</p>

  <div class="sideBarText"><strong>Unattended</strong><br />
    <a href="info-download.php#unattended">info</a> | <a 
       href="http://prdownloads.sourceforge.net/unattended/unattended-4.7.zip?download">download</a>
  </div>
  <div class="sideBarText"><strong>DOS bootdisks</strong><br />
    <a href="info-download.php#unattended-dosboot">info</a> | <a
       href="http://prdownloads.sourceforge.net/unattended/unattended-4.7-dosboot.zip?download" >download</a>
  </div>
  <div class="sideBarText"><strong>linux bootdisk</strong><br />
    <a href="info-download.php#unattended-linuxboot">info</a> | <a
       href="http://prdownloads.sourceforge.net/unattended/unattended-4.7-linuxboot.zip?download" >download</a>
  </div>
  <div class="sideBarText"><strong>support files</strong><br />
    <a href="info-download.php#supportfiles">info</a> | <a 
       href="info-download.php#supportfiles" >download</a></div>
        <?= $addbox ?>
  </div>
