      <!-- ##### Right Sidebar ##### -->


      <div class="rightSideBar doNotPrint">
<!-- news temporarily disabled //
        <p class="sideBarTitle">News</p>

        <div class="sideBarText"><strong>2004-08-06</strong><br />
          Unattended 4.4 released</div>

        <div class="sideBarText"><strong>2004-06-16</strong><br />
          Unattended 4.3 released</div>

        <a href="http://sourceforge.net/news/?group_id=62053"
          class="more">more news &raquo;</a>
// -->
        <p class="sideBarTitle">Downloads</p>

        <div class="sideBarText"><strong>Unattended</strong><br />
          <a href="info-download.php#unattended">info</a> | <a
            href="http://prdownloads.sourceforge.net/unattended/unattended-4.6.zip?download"
            >download</a></div>
        <div class="sideBarText"><strong>DOS bootdisks</strong><br />
          <a href="info-download.php#unattended-dosboot">info</a> | <a
            href="http://prdownloads.sourceforge.net/unattended/unattended-4.6-dosboot.zip?download"
            >download</a></div>
        <div class="sideBarText"><strong>linux bootdisk</strong><br />
          <a href="info-download.php#unattended-linuxboot">info</a> | <a
            href="http://prdownloads.sourceforge.net/unattended/unattended-4.6-linuxboot.zip?download"
            >download</a></div>
        <div class="sideBarText"><strong>support files</strong><br />
          <a href="info-download.php#supportfiles">info</a> | <a
            href="info-download.php#supportfiles"
            >download</a></div>

        <?= $addbox ?>
      </div>
