#!/bin/ash

echo WELCOME!!!

/bin/mkdir /sys
/bin/mount -t sysfs sysfs /sys

/bin/mkdir /proc
/bin/mount -t proc proc /proc

/bin/mkdir /dev/pts
/bin/mount -t devpts devpts /dev/pts

/bin/mkdir /z

# For playing random games
/bin/mkdir /mnt

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

# Fire up shells on virtual consoles 2 and 3
openvt -c 2 bash
openvt -c 3 bash

# Should never return
openvt -f -c 1 -w /etc/master

echo "**** Master script exited!"
exec bash
